#!/usr/local/bin/ruby
require 'wikk_configuration'
require 'wikk_sql'

load '/wikk/etc/wikk.conf' unless defined? WIKK_CONF
require_relative "#{RLIB}/customer/customer.rb"

@mysql_conf = WIKK::Configuration.new(MYSQL_CONF)
WIKK::SQL.connect(@mysql_conf) do |sql_fd|
  puts "Last allocated site id #{last_customer_id(sql: sql_fd)}"
end
